//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicentaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANDIDATE_PROCESS
    {
        public int id_candidate { get; set; }
        public int id_company { get; set; }
        public int id_status { get; set; }
        public int id_process { get; set; }
    
        public virtual CANDIDATE_STATUS CANDIDATE_STATUS { get; set; }
        public virtual CANDIDATES CANDIDATES { get; set; }
        public virtual COMPANIES COMPANIES { get; set; }
    }
}
