//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicentaAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class noBordersEntities : DbContext
    {
        public noBordersEntities()
            : base("name=noBordersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CANDIDATE_PROCESS> CANDIDATE_PROCESS { get; set; }
        public virtual DbSet<CANDIDATE_STATUS> CANDIDATE_STATUS { get; set; }
        public virtual DbSet<CANDIDATES> CANDIDATES { get; set; }
        public virtual DbSet<COMPANIES> COMPANIES { get; set; }
        public virtual DbSet<EDUCATIONS> EDUCATIONS { get; set; }
        public virtual DbSet<EXPERIENCES> EXPERIENCES { get; set; }
        public virtual DbSet<LANGUAGES> LANGUAGES { get; set; }
        public virtual DbSet<REGISTRATION_COMPANY> REGISTRATION_COMPANY { get; set; }
        public virtual DbSet<REGISTRATION_CANDIDATE> REGISTRATION_CANDIDATE { get; set; }
        public virtual DbSet<LOGIN> LOGIN { get; set; }
    }
}
